### ISSUE TITLE
`OpenStack compute binding only supports version v2 and v2.1` error

### ISSUE THREAD

**Issue by cppforlife** [cloudfoundry-incubator/bosh-openstack-cpi-release#111]
following stacktrace came up on our openstack mitaka env using v36 cpi:

```
Rescued Unknown: OpenStack compute binding only supports version v2 and v2.1. backtrace: /home/ubuntu/.bosh/installations/7f4c5a37-ee9b-42ed-5250-6f04bbad8c3e/packages/bosh_openstack_cpi/vendor/bundle/ruby/2.4.0/gems/fog-openstack-0.1.23.pre.microversions/lib/fog/compute/openstack.rb:400:in `initialize'
/home/ubuntu/.bosh/installations/7f4c5a37-ee9b-42ed-5250-6f04bbad8c3e/packages/bosh_openstack_cpi/vendor/bundle/ruby/2.4.0/gems/fog-core-1.45.0/lib/fog/core/service.rb:115:in `new'
/home/ubuntu/.bosh/installations/7f4c5a37-ee9b-42ed-5250-6f04bbad8c3e/packages/bosh_openstack_cpi/vendor/bundle/ruby/2.4.0/gems/fog-core-1.45.0/lib/fog/core/service.rb:115:in `new'
/home/ubuntu/.bosh/installations/7f4c5a37-ee9b-42ed-5250-6f04bbad8c3e/packages/bosh_openstack_cpi/vendor/bundle/ruby/2.4.0/gems/fog-core-1.45.0/lib/fog/core/services_mixin.rb:16:in `new'
/home/ubuntu/.bosh/installations/7f4c5a37-ee9b-42ed-5250-6f04bbad8c3e/packages/bosh_openstack_cpi/vendor/bundle/ruby/2.4.0/gems/fog-core-1.45.0/lib/fog/compute.rb:54:in `new'
/home/ubuntu/.bosh/installations/7f4c5a37-ee9b-42ed-5250-6f04bbad8c3e/packages/bosh_openstack_cpi/lib/cloud/openstack/openstack.rb:109:in `block in compute'
/home/ubuntu/.bosh/installations/7f4c5a37-ee9b-42ed-5250-6f04bbad8c3e/packages/bosh_openstack_cpi/vendor/bundle/ruby/2.4.0/gems/bosh_common-1.3262.24.0/lib/common/retryable.rb:28:in `block in retryer'
/home/ubuntu/.bosh/installations/7f4c5a37-ee9b-42ed-5250-6f04bbad8c3e/packages/bosh_openstack_cpi/vendor/bundle/ruby/2.4.0/gems/bosh_common-1.3262.24.0/lib/common/retryable.rb:26:in `loop'
/home/ubuntu/.bosh/installations/7f4c5a37-ee9b-42ed-5250-6f04bbad8c3e/packages/bosh_openstack_cpi/vendor/bundle/ruby/2.4.0/gems/bosh_common-1.3262.24.0/lib/common/retryable.rb:26:in `retryer'
/home/ubuntu/.bosh/installations/7f4c5a37-ee9b-42ed-5250-6f04bbad8c3e/packages/bosh_openstack_cpi/vendor/bundle/ruby/2.4.0/gems/bosh_common-1.3262.24.0/lib/common/common.rb:119:in `retryable'
/home/ubuntu/.bosh/installations/7f4c5a37-ee9b-42ed-5250-6f04bbad8c3e/packages/bosh_openstack_cpi/lib/cloud/openstack/openstack.rb:107:in `compute'
/home/ubuntu/.bosh/installations/7f4c5a37-ee9b-42ed-5250-6f04bbad8c3e/packages/bosh_openstack_cpi/lib/cloud/openstack/security_groups.rb:23:in `retrieve_security_groups'
/home/ubuntu/.bosh/installations/7f4c5a37-ee9b-42ed-5250-6f04bbad8c3e/packages/bosh_openstack_cpi/lib/cloud/openstack/security_groups.rb:13:in `block in select_and_retrieve'
/home/ubuntu/.bosh/installations/7f4c5a37-ee9b-42ed-5250-6f04bbad8c3e/packages/bosh_openstack_cpi/lib/cloud/openstack/openstack.rb:45:in `with_openstack'
/home/ubuntu/.bosh/installations/7f4c5a37-ee9b-42ed-5250-6f04bbad8c3e/packages/bosh_openstack_cpi/lib/cloud/openstack/security_groups.rb:12:in `select_and_retrieve'
/home/ubuntu/.bosh/installations/7f4c5a37-ee9b-42ed-5250-6f04bbad8c3e/packages/bosh_openstack_cpi/lib/cloud/openstack/cloud.rb:617:in `pick_security_groups'
/home/ubuntu/.bosh/installations/7f4c5a37-ee9b-42ed-5250-6f04bbad8c3e/packages/bosh_openstack_cpi/lib/cloud/openstack/cloud.rb:145:in `block in create_vm'
/home/ubuntu/.bosh/installations/7f4c5a37-ee9b-42ed-5250-6f04bbad8c3e/packages/bosh_openstack_cpi/vendor/bundle/ruby/2.4.0/gems/bosh_common-1.3262.24.0/lib/common/thread_formatter.rb:49:in `with_thread_name'
/home/ubuntu/.bosh/installations/7f4c5a37-ee9b-42ed-5250-6f04bbad8c3e/packages/bosh_openstack_cpi/lib/cloud/openstack/cloud.rb:135:in `create_vm'
/home/ubuntu/.bosh/installations/7f4c5a37-ee9b-42ed-5250-6f04bbad8c3e/packages/bosh_openstack_cpi/vendor/bundle/ruby/2.4.0/gems/bosh_cpi-2.3.0/lib/bosh/cpi/cli.rb:82:in `public_send'
/home/ubuntu/.bosh/installations/7f4c5a37-ee9b-42ed-5250-6f04bbad8c3e/packages/bosh_openstack_cpi/vendor/bundle/ruby/2.4.0/gems/bosh_cpi-2.3.0/lib/bosh/cpi/cli.rb:82:in `run'
/home/ubuntu/.bosh/installations/7f4c5a37-ee9b-42ed-5250-6f04bbad8c3e/packages/bosh_openstack_cpi/bin/openstack_cpi:21:in `block in <top (required)>'
/home/ubuntu/.bosh/installations/7f4c5a37-ee9b-42ed-5250-6f04bbad8c3e/packages/ruby_openstack_cpi/lib/ruby/2.4.0/tmpdir.rb:89:in `mktmpdir'
/home/ubuntu/.bosh/installations/7f4c5a37-ee9b-42ed-5250-6f04bbad8c3e/packages/bosh_openstack_cpi/bin/openstack_cpi:17:in `<top (required)>'
/home/ubuntu/.bosh/installations/7f4c5a37-ee9b-42ed-5250-6f04bbad8c3e/packages/ruby_openstack_cpi/lib/ruby/site_ruby/2.4.0/bundler/cli/exec.rb:75:in `load'
/home/ubuntu/.bosh/installations/7f4c5a37-ee9b-42ed-5250-6f04bbad8c3e/packages/ruby_openstack_cpi/lib/ruby/site_ruby/2.4.0/bundler/cli/exec.rb:75:in `kernel_load'
/home/ubuntu/.bosh/installations/7f4c5a37-ee9b-42ed-5250-6f04bbad8c3e/packages/ruby_openstack_cpi/lib/ruby/site_ruby/2.4.0/bundler/cli/exec.rb:28:in `run'
/home/ubuntu/.bosh/installations/7f4c5a37-ee9b-42ed-5250-6f04bbad8c3e/packages/ruby_openstack_cpi/lib/ruby/site_ruby/2.4.0/bundler/cli.rb:424:in `exec'
/home/ubuntu/.bosh/installations/7f4c5a37-ee9b-42ed-5250-6f04bbad8c3e/packages/ruby_openstack_cpi/lib/ruby/site_ruby/2.4.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/home/ubuntu/.bosh/installations/7f4c5a37-ee9b-42ed-5250-6f04bbad8c3e/packages/ruby_openstack_cpi/lib/ruby/site_ruby/2.4.0/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/home/ubuntu/.bosh/installations/7f4c5a37-ee9b-42ed-5250-6f04bbad8c3e/packages/ruby_openstack_cpi/lib/ruby/site_ruby/2.4.0/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
/home/ubuntu/.bosh/installations/7f4c5a37-ee9b-42ed-5250-6f04bbad8c3e/packages/ruby_openstack_cpi/lib/ruby/site_ruby/2.4.0/bundler/cli.rb:27:in `dispatch'
/home/ubuntu/.bosh/installations/7f4c5a37-ee9b-42ed-5250-6f04bbad8c3e/packages/ruby_openstack_cpi/lib/ruby/site_ruby/2.4.0/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
/home/ubuntu/.bosh/installations/7f4c5a37-ee9b-42ed-5250-6f04bbad8c3e/packages/ruby_openstack_cpi/lib/ruby/site_ruby/2.4.0/bundler/cli.rb:18:in `start'
/home/ubuntu/.bosh/installations/7f4c5a37-ee9b-42ed-5250-6f04bbad8c3e/packages/ruby_openstack_cpi/lib/ruby/gems/2.4.0/gems/bundler-1.16.0/exe/bundle:30:in `block in <top (required)>'
/home/ubuntu/.bosh/installations/7f4c5a37-ee9b-42ed-5250-6f04bbad8c3e/packages/ruby_openstack_cpi/lib/ruby/site_ruby/2.4.0/bundler/friendly_errors.rb:122:in `with_friendly_errors'
/home/ubuntu/.bosh/installations/7f4c5a37-ee9b-42ed-5250-6f04bbad8c3e/packages/ruby_openstack_cpi/lib/ruby/gems/2.4.0/gems/bundler-1.16.0/exe/bundle:22:in `<top (required)>'
/home/ubuntu/.bosh/installations/7f4c5a37-ee9b-42ed-5250-6f04bbad8c3e/packages/ruby_openstack_cpi/bin/bundle:23:in `load'
/home/ubuntu/.bosh/installations/7f4c5a37-ee9b-42ed-5250-6f04bbad8c3e/packages/ruby_openstack_cpi/bin/bundle:23:in `<main>'
```

following is the catalog returned:

```
"serviceCatalog": [
      {
        "endpoints": [
          {
            "adminURL": "http://192.168.161.2:8774/v2.1",
            "region": "RegionOne",
            "internalURL": "http://192.168.161.2:8774/v2.1",
            "id": "14a2dcc3b7ae4fa69a00739a273a5d94",
            "publicURL": "http://10.87.16.4:8774/v2.1"
          }
        ],
        "endpoints_links": [],
        "type": "compute",
        "name": "nova"
      },
      {
        "endpoints": [
          {
            "adminURL": "http://192.168.161.2:9696",
            "region": "RegionOne",
            "internalURL": "http://192.168.161.2:9696",
            "id": "62bb903019824bb8bc015eae967cb575",
            "publicURL": "http://10.87.16.4:9696"
          }
        ],
        "endpoints_links": [],
        "type": "network",
        "name": "neutron"
      },
      {
        "endpoints": [
          {
            "adminURL": "http://192.168.161.2:8776/v2/c1b58b3e1cf0485385495abb898adeca",
            "region": "RegionOne",
            "internalURL": "http://192.168.161.2:8776/v2/c1b58b3e1cf0485385495abb898adeca",
            "id": "0ee3b7e019c841389a1f600679758beb",
            "publicURL": "http://10.87.16.4:8776/v2/c1b58b3e1cf0485385495abb898adeca"
          }
        ],
        "endpoints_links": [],
        "type": "volumev2",
        "name": "cinderv2"
      },
      {
        "endpoints": [
          {
            "adminURL": "http://192.168.161.2:8776/v3/c1b58b3e1cf0485385495abb898adeca",
            "region": "RegionOne",
            "internalURL": "http://192.168.161.2:8776/v3/c1b58b3e1cf0485385495abb898adeca",
            "id": "6ec3b2ad92624ff2b2c07183290224a7",
            "publicURL": "http://10.87.16.4:8776/v3/c1b58b3e1cf0485385495abb898adeca"
          }
        ],
        "endpoints_links": [],
        "type": "volumev3",
        "name": "cinderv3"
      },
      {
        "endpoints": [
          {
            "adminURL": "http://192.168.161.2:8080",
            "region": "RegionOne",
            "internalURL": "http://192.168.161.2:8080",
            "id": "0c7d542af79448e8863b63315026d74d",
            "publicURL": "http://10.87.16.4:8080"
          }
        ],
        "endpoints_links": [],
        "type": "s3",
        "name": "swift_s3"
      },
      {
        "endpoints": [
          {
            "adminURL": "http://192.168.161.2:8042",
            "region": "RegionOne",
            "internalURL": "http://192.168.161.2:8042",
            "id": "5faa91de7ddd4d8cbc790e9605210b0a",
            "publicURL": "http://10.87.16.4:8042"
          }
        ],
        "endpoints_links": [],
        "type": "alarming",
        "name": "aodh"
      },
      {
        "endpoints": [
          {
            "adminURL": "http://192.168.161.2:9292",
            "region": "RegionOne",
            "internalURL": "http://192.168.161.2:9292",
            "id": "51f09fb7ded84b3284ee1964679a7ba9",
            "publicURL": "http://10.87.16.4:9292"
          }
        ],
        "endpoints_links": [],
        "type": "image",
        "name": "glance"
      },
      {
        "endpoints": [
          {
            "adminURL": "http://192.168.161.2:8777",
            "region": "RegionOne",
            "internalURL": "http://192.168.161.2:8777",
            "id": "15a1b630192a42deb97ae644145b6458",
            "publicURL": "http://10.87.16.4:8777"
          }
        ],
        "endpoints_links": [],
        "type": "metering",
        "name": "ceilometer"
      },
      {
        "endpoints": [
          {
            "adminURL": "http://192.168.161.2:9494",
            "region": "RegionOne",
            "internalURL": "http://192.168.161.2:9494",
            "id": "6c6e1d517b3c4d63b1a1a198298b7b7d",
            "publicURL": "http://10.87.16.4:9494"
          }
        ],
        "endpoints_links": [],
        "type": "artifact",
        "name": "glare"
      },
      {
        "endpoints": [
          {
            "adminURL": "http://192.168.161.2:8774/v2/c1b58b3e1cf0485385495abb898adeca",
            "region": "RegionOne",
            "internalURL": "http://192.168.161.2:8774/v2/c1b58b3e1cf0485385495abb898adeca",
            "id": "185f75a888ac492a8c39fe92fbe66149",
            "publicURL": "http://10.87.16.4:8774/v2/c1b58b3e1cf0485385495abb898adeca"
          }
        ],
        "endpoints_links": [],
        "type": "compute_legacy",
        "name": "compute_legacy"
      },
      {
        "endpoints": [
          {
            "adminURL": "http://192.168.161.2:8776/v1/c1b58b3e1cf0485385495abb898adeca",
            "region": "RegionOne",
            "internalURL": "http://192.168.161.2:8776/v1/c1b58b3e1cf0485385495abb898adeca",
            "id": "84750c84f7044b4a9201b897ef86095d",
            "publicURL": "http://10.87.16.4:8776/v1/c1b58b3e1cf0485385495abb898adeca"
          }
        ],
        "endpoints_links": [],
        "type": "volume",
        "name": "cinder"
      },
      {
        "endpoints": [
          {
            "adminURL": "http://192.168.161.2:8000/v1",
            "region": "RegionOne",
            "internalURL": "http://192.168.161.2:8000/v1",
            "id": "a54a036885614a6bad4a8df28cf4db35",
            "publicURL": "http://10.87.16.4:8000/v1"
          }
        ],
        "endpoints_links": [],
        "type": "cloudformation",
        "name": "heat-cfn"
      },
      {
        "endpoints": [
          {
            "adminURL": "http://192.168.161.2:8004/v1/c1b58b3e1cf0485385495abb898adeca",
            "region": "RegionOne",
            "internalURL": "http://192.168.161.2:8004/v1/c1b58b3e1cf0485385495abb898adeca",
            "id": "16613a1f25a143a08577913210b79447",
            "publicURL": "http://10.87.16.4:8004/v1/c1b58b3e1cf0485385495abb898adeca"
          }
        ],
        "endpoints_links": [],
        "type": "orchestration",
        "name": "heat"
      },
      {
        "endpoints": [
          {
            "adminURL": "http://192.168.161.2:8080/swift/v1",
            "region": "RegionOne",
            "internalURL": "http://192.168.161.2:8080/swift/v1",
            "id": "0770027015cb4d98a1872b653ab2c6aa",
            "publicURL": "http://10.87.16.4:8080/swift/v1"
          }
        ],
        "endpoints_links": [],
        "type": "object-store",
        "name": "swift"
      },
      {
        "endpoints": [
          {
            "adminURL": "http://192.168.161.2:35357/v2.0",
            "region": "RegionOne",
            "internalURL": "http://192.168.161.2:5000/v2.0",
            "id": "0332355305b14d71ab8aa5b82b417ecc",
            "publicURL": "http://10.87.16.4:5000/v2.0"
          }
        ],
        "endpoints_links": [],
        "type": "identity",
        "name": "keystone"
      }
    ],
```

**Comment by voelzmo** [comment]
Seems like this is a bug in our regex implementation which matches the compute URL. We'll provide a fix soon.

**Comment by voelzmo** [comment]
Fixed with [v37](https://github.com/cloudfoundry-incubator/bosh-openstack-cpi-release/releases/tag/v37)

**Comment by markosluga** [comment]
Hi, when changing the CPI to v37 I get the following error when downloading the bosh cpi:

 Downloading release 'bosh-openstack-cpi'... Failed (00:01:21)
Failed validating (00:01:24)

Failed to download from 'https://bosh.io/d/github.com/cloudfoundry-incubator/bosh-openstack-cpi-release?v=37':
  Verifying digest for downloaded file:
    Expected stream to have digest '13a67e486b8c62dda48b13dd2b5c8ac16724934c' but was '4507b907955909bc8036afc1cf6be339b306ca03'

Exit code 1

**Comment by genevieve** [comment]
Going to bump the version of the cpi in jumpbox-deployment since I am seeing this trying to deploy the jumpbox with bbl right now. Sound good @cppforlife ?

**Comment by cppforlife** [comment]
yup.
