### ISSUE TITLE
Problem when install bucc to openstack : Openssl error

### ISSUE THREAD

**Issue by jyriok** [cloudfoundry-incubator/bosh-openstack-cpi-release#121]
Hello,

I try to install BUCC on a iaas Openstack but i've error with openssl lib :

```
stdout: 'bundler: failed to load command: /home/ubuntu/.bosh/installations/82bac5cf-b7a5-443d-71d9-20d99f15b4b5/packages/bosh_openstack_cpi/bin/openstack_cpi (/home/ubuntu/.bosh/installations/82bac5cf-b7a5-443d-71d9-20d99f15b4b5/packages/bosh_openstack_cpi/bin/openstack_cpi)
', stderr: 'LoadError: cannot load such file -- openssl
```
but
:
```
dpkg -l | grep ssl
ii  libflac8:amd64                   1.3.1-4                                    amd64        Free Lossless Audio Codec - runtime C library
ii  libgnutls-openssl27:amd64        3.4.10-4ubuntu1.4                          amd64        GNU TLS library - OpenSSL wrapper
ii  libssl-dev:amd64                 1.0.2g-1ubuntu4.10                         amd64        Secure Sockets Layer toolkit - development files
ii  libssl-doc                       1.0.2g-1ubuntu4.10                         all          Secure Sockets Layer toolkit - development documentation
ii  libssl1.0.0:amd64                1.0.2g-1ubuntu4.10                         amd64        Secure Sockets Layer toolkit - shared libraries
ii  openssl                          1.0.2g-1ubuntu4.10                         amd64        Secure Sockets Layer toolkit - cryptographic utility

```

and 

ruby and openssl is install and works :
```
ruby -ropenssl -e "puts :OK"
OK
```

and i've all the bosh dependencies installed :

```
sudo apt-get install -y build-essential zlibc zlib1g-dev ruby ruby-dev openssl libxslt-dev libxml2-dev libssl-dev libreadline6 libreadline6-dev libyaml-dev libsqlite3-dev sqlite3
sudo: unable to resolve host bucc
Reading package lists... Done
Building dependency tree
Reading state information... Done
Note, selecting 'libxslt1-dev' instead of 'libxslt-dev'
build-essential is already the newest version (12.1ubuntu2).
libreadline6 is already the newest version (6.3-8ubuntu2).
libreadline6-dev is already the newest version (6.3-8ubuntu2).
libsqlite3-dev is already the newest version (3.11.0-1ubuntu1).
libyaml-dev is already the newest version (0.1.6-3).
ruby is already the newest version (1:2.3.0+1).
ruby-dev is already the newest version (1:2.3.0+1).
sqlite3 is already the newest version (3.11.0-1ubuntu1).
zlibc is already the newest version (0.9k-4.3).
libssl-dev is already the newest version (1.0.2g-1ubuntu4.10).
libxml2-dev is already the newest version (2.9.3+dfsg1-1ubuntu0.5).
libxslt1-dev is already the newest version (1.1.28-2.1ubuntu0.1).
openssl is already the newest version (1.0.2g-1ubuntu4.10).
zlib1g-dev is already the newest version (1:1.2.8.dfsg-2ubuntu4.1).
0 upgraded, 0 newly installed, 0 to remove and 5 not upgraded.
```

Can you help me ? 

```
 bin/bucc  up --cpi openstack --keystone-v2
Using flags: --cpi openstack --keystone-v2
Flag files: '/home/ubuntu/BUCC/bucc/state/{cpi,lite,flags}'

Deployment manifest: '/home/ubuntu/BUCC/bucc/src/bosh-deployment/bosh.yml'
Deployment state: '/home/ubuntu/BUCC/bucc/state/state.json'

Started validating
  Downloading release 'bosh'... Skipped [Found in local cache] (00:00:00)
  Validating release 'bosh'... Finished (00:00:00)
  Downloading release 'bosh-openstack-cpi'... Skipped [Found in local cache] (00:00:00)
  Validating release 'bosh-openstack-cpi'... Finished (00:00:00)
  Downloading release 'os-conf'... Skipped [Found in local cache] (00:00:00)
  Validating release 'os-conf'... Finished (00:00:00)
  Downloading release 'garden-runc'... Skipped [Found in local cache] (00:00:00)
  Validating release 'garden-runc'... Finished (00:00:00)
  Downloading release 'uaa'... Skipped [Found in local cache] (00:00:00)
  Validating release 'uaa'... Finished (00:00:01)
  Downloading release 'concourse'... Skipped [Found in local cache] (00:00:00)
  Validating release 'concourse'... Finished (00:00:03)
  Downloading release 'credhub'... Skipped [Found in local cache] (00:00:00)
  Validating release 'credhub'... Finished (00:00:00)
  Downloading release 'credhub-importer'... Skipped [Found in local cache] (00:00:00)
  Validating release 'credhub-importer'... Finished (00:00:00)
  Downloading release 'postgres'... Skipped [Found in local cache] (00:00:00)
  Validating release 'postgres'... Finished (00:00:00)
  Downloading release 'bucc-bbr'... Skipped [Found in local cache] (00:00:00)
  Validating release 'bucc-bbr'... Finished (00:00:01)
  Validating cpi release... Finished (00:00:00)
  Validating deployment manifest... Finished (00:00:00)
  Downloading stemcell... Skipped [Found in local cache] (00:00:00)
  Validating stemcell... Finished (00:00:02)
Finished validating (00:00:13)

Started installing CPI
  Compiling package 'ruby_openstack_cpi/ddb0f4a3013923fb1b074454d4314264c47d33c5'... Finished (00:00:00)
  Compiling package 'bosh_openstack_cpi/2ae4a479317fcc7300eda9125fa4572ec9a20e82'... Finished (00:00:00)
  Installing packages... Finished (00:00:00)
  Rendering job templates... Finished (00:00:00)
  Installing job 'openstack_cpi'... Finished (00:00:00)
Finished installing CPI (00:00:00)

Starting registry... Finished (00:00:00)
Uploading stemcell 'bosh-openstack-kvm-ubuntu-trusty-go_agent/3468.21'... Failed (00:00:00)
Stopping registry... Finished (00:00:00)
Cleaning up rendered CPI jobs... Finished (00:00:00)

creating stemcell (bosh-openstack-kvm-ubuntu-trusty-go_agent 3468.21):
  Executing external CPI command: '/home/ubuntu/.bosh/installations/82bac5cf-b7a5-443d-71d9-20d99f15b4b5/jobs/openstack_cpi/bin/cpi':
    Running command: '/home/ubuntu/.bosh/installations/82bac5cf-b7a5-443d-71d9-20d99f15b4b5/jobs/openstack_cpi/bin/cpi', stdout: 'bundler: failed to load command: /home/ubuntu/.bosh/installations/82bac5cf-b7a5-443d-71d9-20d99f15b4b5/packages/bosh_openstack_cpi/bin/openstack_cpi (/home/ubuntu/.bosh/installations/82bac5cf-b7a5-443d-71d9-20d99f15b4b5/packages/bosh_openstack_cpi/bin/openstack_cpi)
', stderr: 'LoadError: cannot load such file -- openssl
  /home/ubuntu/.bosh/installations/82bac5cf-b7a5-443d-71d9-20d99f15b4b5/packages/bosh_openstack_cpi/vendor/bundle/ruby/2.4.0/gems/excon-0.60.0/lib/excon.rb:7:in `require'
  /home/ubuntu/.bosh/installations/82bac5cf-b7a5-443d-71d9-20d99f15b4b5/packages/bosh_openstack_cpi/vendor/bundle/ruby/2.4.0/gems/excon-0.60.0/lib/excon.rb:7:in `<top (required)>'
  /home/ubuntu/.bosh/installations/82bac5cf-b7a5-443d-71d9-20d99f15b4b5/packages/bosh_openstack_cpi/vendor/bundle/ruby/2.4.0/gems/fog-core-1.45.0/lib/fog/core.rb:5:in `require'
  /home/ubuntu/.bosh/installations/82bac5cf-b7a5-443d-71d9-20d99f15b4b5/packages/bosh_openstack_cpi/vendor/bundle/ruby/2.4.0/gems/fog-core-1.45.0/lib/fog/core.rb:5:in `<top (required)>'
  /home/ubuntu/.bosh/installations/82bac5cf-b7a5-443d-71d9-20d99f15b4b5/packages/bosh_openstack_cpi/vendor/bundle/ruby/2.4.0/gems/fog-openstack-0.1.24/lib/fog/openstack.rb:2:in `require'
  /home/ubuntu/.bosh/installations/82bac5cf-b7a5-443d-71d9-20d99f15b4b5/packages/bosh_openstack_cpi/vendor/bundle/ruby/2.4.0/gems/fog-openstack-0.1.24/lib/fog/openstack.rb:2:in `<top (required)>'
  /home/ubuntu/.bosh/installations/82bac5cf-b7a5-443d-71d9-20d99f15b4b5/packages/bosh_openstack_cpi/lib/cloud/openstack.rb:5:in `require'
  /home/ubuntu/.bosh/installations/82bac5cf-b7a5-443d-71d9-20d99f15b4b5/packages/bosh_openstack_cpi/lib/cloud/openstack.rb:5:in `<top (required)>'
  /home/ubuntu/.bosh/installations/82bac5cf-b7a5-443d-71d9-20d99f15b4b5/packages/bosh_openstack_cpi/bin/openstack_cpi:7:in `require'
  /home/ubuntu/.bosh/installations/82bac5cf-b7a5-443d-71d9-20d99f15b4b5/packages/bosh_openstack_cpi/bin/openstack_cpi:7:in `<top (required)>'
':
      exit status 1

Exit code 1
```

**Comment by jyriok** [comment]
it's for :
bosh-openstack-cpi  release  38

**Comment by voelzmo** [comment]
Hey, @jyriok,

Thanks for reporting this. On which version of Ubuntu are you running this? I don't have any experience with `bucc`, so could you try not using it and switch to the standard way of deploying on OpenStack [as described by the docs] (https://bosh.io/docs/init-openstack.html)? Just to figure out if the issue is with `bucc` or if we have a general problem on certain Ubuntu versions.

Thanks!

**Comment by jyriok** [comment]
thanks for your quick answer :)
i try this on a Ubuntu 16.04.4 LTS

i've open this to bucc too   : https://github.com/starkandwayne/bucc/issues/102 

i've just tested with Ubuntu 14.04.4 LTS and that's works :)

so for me, i will use 14.04 because i've no problem and i can close this issue or if you want, i let it open and help if you want make some test for see what's wrong

**Comment by ramonskie** [comment]
do you use rvm?
what global ruby version do you use
whats the output of `ruby -v` in the bucc repo

**Comment by jyriok** [comment]
```
rvm version
rvm 1.29.3 (latest) by Michal Papis, Piotr Kuczynski, Wayne E. Seguin [https://rvm.io]
```
```
ruby -v
ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-linux]
```

**Comment by ramonskie** [comment]
what is the ruby version your using in the ubuntu 14.04 where your setup does work?

**Comment by jyriok** [comment]
for ubuntu 14.04 i have 

```
rvm info

ruby-2.4.1:

  system:
    uname:        "Linux tlstncfjbx01 3.13.0-74-generic #118-Ubuntu SMP Thu Dec 17 22:52:10 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux"
    name:         "Ubuntu"
    version:      "14.04"
    architecture: "x86_64"
    bash:         "/bin/bash => GNU bash, version 4.3.11(1)-release (x86_64-pc-linux-gnu)"
    zsh:          " => not installed"
    remote_path:  "ubuntu/14.04/x86_64"

  rvm:
    version:      "1.29.3 (latest)"
    updated:      "1 month 17 days 3 hours 23 minutes 43 seconds ago"
    path:         "/home/ubuntu/.rvm"
    autolibs:     "[4] Allow RVM to use package manager if found, install missing dependencies, install package manager (only OS X)."

  ruby:
    interpreter:  "ruby"
    version:      "2.4.1p111"
    date:         "2017-03-22"
    platform:     "x86_64-linux"
    patchlevel:   "2017-03-22 revision 58053"
    full_version: "ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-linux]"

  homes:
    gem:          "/home/ubuntu/.rvm/gems/ruby-2.4.1"
    ruby:         "/home/ubuntu/.rvm/rubies/ruby-2.4.1"

  binaries:
    ruby:         "/home/ubuntu/.rvm/rubies/ruby-2.4.1/bin/ruby"
    irb:          "/home/ubuntu/.rvm/rubies/ruby-2.4.1/bin/irb"
    gem:          "/home/ubuntu/.rvm/rubies/ruby-2.4.1/bin/gem"
    rake:         "/home/ubuntu/.rvm/rubies/ruby-2.4.1/bin/rake"

  environment:
    PATH:         "/home/ubuntu/.rvm/gems/ruby-2.4.1/bin:/home/ubuntu/.rvm/gems/ruby-2.4.1@global/bin:/home/ubuntu/.rvm/rubies/ruby-2.4.1/bin:/home/ubuntu/.rbenv/shims:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home/ubuntu/.rbenv/bin:/usr/local/go/bin:/home/ubuntu/Workspace/golang/bin:/home/ubuntu/.rvm/bin:/home/ubuntu/.rvm/bin:/home/ubuntu/.rvm/bin"
    GEM_HOME:     "/home/ubuntu/.rvm/gems/ruby-2.4.1"
    GEM_PATH:     "/home/ubuntu/.rvm/gems/ruby-2.4.1:/home/ubuntu/.rvm/gems/ruby-2.4.1@global"
    MY_RUBY_HOME: "/home/ubuntu/.rvm/rubies/ruby-2.4.1"
    IRBRC:        "/home/ubuntu/.rvm/rubies/ruby-2.4.1/.irbrc"
    RUBYOPT:      ""
    gemset:       ""

```

**Comment by ramonskie** [comment]
can you try to use the 2.4.1 instead of the 2.4.1p111
or maby even 2.4.0

**Comment by jyriok** [comment]
i can't test it anymore, the server with 16.04 is gone and we use instead the 14.04 , so for me, actually, all is ok (for 14.04) 
i close this issue, maybe i made something wrong with 16.04 or maybe i touch a incompatibility but i think , if the problem still exist, another person will open a new issue. we will see

thanks for yours support

**Comment by vChrisR** [comment]
I am using 16.04 as well and get the exact same error. All dependencies are there but it won't work.
I am not using BUCC, just using bosh-deployment.

**Comment by ramonskie** [comment]
did you checked the ruby versions?

**Comment by vChrisR** [comment]
tried the one that gets installed using _apt-get installl ruby_ first (2.3.1 I believe). Then tried 2.5.x

Just deleted the box with 16.04 and launching a 14.04 instance now. Just need to get it working. but I can try 16.04 again later if you need more details.
