### ISSUE TITLE
Error handling when token expires in the middle of creating a stemcell

### ISSUE THREAD

**Issue by tomoe** [cloudfoundry-incubator/bosh-openstack-cpi-release#40]
I get the following error when creating a stemcell took a log time and the token expired in the middle of the creation. 
I'd expect it to regenerate a token, and continue the work, but it is blowing up. 

```
:reason_phrase => \"Multiple Choices\"\n
:status        => 300\n
:status_line   => \"HTTP/1.1 300 Multiple Choices\\r\\n\"\n.
backtrace: /home/tempest-web/.bosh_init/installations/636c5a9d-a4d2-4e01-7a18-943c42f5758d/packages/bosh_openstack_cpi/vendor/bundle/ruby/2.1.0/gems/excon-0.45.4/lib/excon/middlewares/expects.rb:6:in `response_call'\n
/home/tempest-web/.bosh_init/installations/636c5a9d-a4d2-4e01-7a18-943c42f5758d/packages/bosh_openstack_cpi/vendor/bundle/ruby/2.1.0/gems/excon-0.45.4/lib/excon/middlewares/response_parser.rb:8:in `response_call'\n
/home/tempest-web/.bosh_init/installations/636c5a9d-a4d2-4e01-7a18-943c42f5758d/packages/bosh_openstack_cpi/vendor/bundle/ruby/2.1.0/gems/excon-0.45.4/lib/excon/connection.rb:372:in `response'\n
/home/tempest-web/.bosh_init/installations/636c5a9d-a4d2-4e01-7a18-943c42f5758d/packages/bosh_openstack_cpi/vendor/bundle/ruby/2.1.0/gems/excon-0.45.4/lib/excon/connection.rb:236:in `request'\n
/home/tempest-web/.bosh_init/installations/636c5a9d-a4d2-4e01-7a18-943c42f5758d/packages/bosh_openstack_cpi/vendor/bundle/ruby/2.1.0/gems/fog-core-1.32.1/lib/fog/core/connection.rb:81:in `request'\n
/home/tempest-web/.bosh_init/installations/636c5a9d-a4d2-4e01-7a18-943c42f5758d/packages/bosh_openstack_cpi/vendor/bundle/ruby/2.1.0/gems/fog-1.34.0/lib/fog/openstack/image.rb:123:in `request'\n
/home/tempest-web/.bosh_init/installations/636c5a9d-a4d2-4e01-7a18-943c42f5758d/packages/bosh_openstack_cpi/vendor/bundle/ruby/2.1.0/gems/fog-1.34.0/lib/fog/openstack/requests/image/list_public_images_detailed.rb:16:in `list_public_images_detailed'\n
/home/tempest-web/.bosh_init/installations/636c5a9d-a4d2-4e01-7a18-943c42f5758d/packages/bosh_openstack_cpi/vendor/bundle/ruby/2.1.0/gems/fog-1.34.0/lib/fog/openstack/models/image/images.rb:11:in `all'\n
/home/tempest-web/.bosh_init/installations/636c5a9d-a4d2-4e01-7a18-943c42f5758d/packages/bosh_openstack_cpi/vendor/bundle/ruby/2.1.0/gems/fog-1.34.0/lib/fog/openstack/models/image/images.rb:25:in `find_by_id'\n
/home/tempest-web/.bosh_init/installations/636c5a9d-a4d2-4e01-7a18-943c42f5758d/packages/bosh_openstack_cpi/vendor/bundle/ruby/2.1.0/gems/fog-core-1.32.1/lib/fog/core/model.rb:43:in `reload'\n
/home/tempest-web/.bosh_init/installations/636c5a9d-a4d2-4e01-7a18-943c42f5758d/packages/bosh_openstack_cpi/lib/cloud/openstack/helpers.rb:120:in `block (2 levels) in wait_resource'\n
/home/tempest-web/.bosh_init/installations/636c5a9d-a4d2-4e01-7a18-943c42f5758d/packages/bosh_openstack_cpi/lib/cloud/openstack/helpers.rb:26:in `with_openstack'\n
/home/tempest-web/.bosh_init/installations/636c5a9d-a4d2-4e01-7a18-943c42f5758d/packages/bosh_openstack_cpi/lib/cloud/openstack/helpers.rb:120:in `block in wait_resource'\n
/home/tempest-web/.bosh_init/installations/636c5a9d-a4d2-4e01-7a18-943c42f5758d/packages/bosh_openstack_cpi/lib/cloud/openstack/helpers.rb:106:in `loop'\n
/home/tempest-web/.bosh_init/installations/636c5a9d-a4d2-4e01-7a18-943c42f5758d/packages/bosh_openstack_cpi/lib/cloud/openstack/helpers.rb:106:in `wait_resource'\n
/home/tempest-web/.bosh_init/installations/636c5a9d-a4d2-4e01-7a18-943c42f5758d/packages/bosh_openstack_cpi/lib/cloud/openstack/cloud.rb:162:in `block (2 levels) in create_stemcell'\n
/home/tempest-web/.bosh_init/installations/636c5a9d-a4d2-4e01-7a18-943c42f5758d/packages/ruby_openstack_cpi/lib/ruby/2.1.0/tmpdir.rb:88:in `mktmpdir'\n
/home/tempest-web/.bosh_init/installations/636c5a9d-a4d2-4e01-7a18-943c42f5758d/packages/bosh_openstack_cpi/lib/cloud/openstack/cloud.rb:127:in `block in create_stemcell'\n
/home/tempest-web/.bosh_init/installations/636c5a9d-a4d2-4e01-7a18-943c42f5758d/packages/bosh_openstack_cpi/vendor/bundle/ruby/2.1.0/gems/bosh_common-1.3093.0/lib/common/thread_formatter.rb:49:in `with_thread_name'\n
/home/tempest-web/.bosh_init/installations/636c5a9d-a4d2-4e01-7a18-943c42f5758d/packages/bosh_openstack_cpi/lib/cloud/openstack/cloud.rb:125:in `create_stemcell'\n
/home/tempest-web/.bosh_init/installations/636c5a9d-a4d2-4e01-7a18-943c42f5758d/packages/bosh_openstack_cpi/vendor/bundle/ruby/2.1.0/gems/bosh_cpi-1.3093.0/lib/bosh/cpi/cli.rb:71:in `public_send'\n
/home/tempest-web/.bosh_init/installations/636c5a9d-a4d2-4e01-7a18-943c42f5758d/packages/bosh_openstack_cpi/vendor/bundle/ruby/2.1.0/gems/bosh_cpi-1.3093.0/lib/bosh/cpi/cli.rb:71:in `run'\n
/home/tempest-web/.bosh_init/installations/636c5a9d-a4d2-4e01-7a18-943c42f5758d/packages/bosh_openstack_cpi/bin/openstack_cpi:37:in `<main>'"
```

Relevant logs on the glance-api side:

```
2016-06-17 11:21:32.203 6421 INFO glance.api.v1.images [req-9438099a-12ea-4998-8222-25a96bad202c 462243f565534c5e96ab4d3602e665d8 943a680c99b24c6a884685dc0a335352 - - -] Uploaded data of image 7417decc-ec78-473c-b994-8cbe1d4ed819 from request payload successfully.
2016-06-17 11:21:33.278 6421 INFO eventlet.wsgi.server [req-9438099a-12ea-4998-8222-25a96bad202c 462243f565534c5e96ab4d3602e665d8 943a680c99b24c6a884685dc0a335352 - - -] 192.168.0.2 - - [17/Jun/2016 11:21:33] "POST /v1.1/images HTTP/1.1" 201 1024 11456.519359
2016-06-17 11:21:33.451 6421 WARNING keystonemiddleware.auth_token [-] Authorization failed for token
2016-06-17 11:21:33.452 6421 WARNING keystonemiddleware.auth_token [-] Identity response: {"error": {"message": "Failed to validate token", "code": 404, "title": "Not Found"}}
2016-06-17 11:21:33.452 6421 WARNING keystonemiddleware.auth_token [-] Authorization failed for token
2016-06-17 11:21:33.453 6421 INFO eventlet.wsgi.server [-] 192.168.0.2 - - [17/Jun/2016 11:21:33] "GET /v1.1/images/detail HTTP/1.1" 401 459 0.169943
2016-06-17 11:21:33.526 6420 INFO eventlet.wsgi.server [-] 192.168.0.2 - - [17/Jun/2016 11:21:33] "GET /images/detail HTTP/1.1" 300 817 0.000842
```

**Comment by cppforlife** [comment]
@loewenstein this was from v23 which used fog gem (not fog-openstack). did you see the same problem with fog-openstack?

**Comment by loewenstein** [comment]
@cppforlife interesting, I didn't know/notice this was for v23. The code path I have seen in fog-openstack matches the above OpenStack log quite well (401 followed by 300 with a path missing the v1.1 in the request) so I still expect the problem exists in fog-openstack as well.

**Comment by tomoe** [comment]
Thanks @loewenstein for following up.  Found an issue you've created for this, which I'm adding a link here:https://github.com/fog/fog-openstack/issues/148

**Comment by cppforlife** [comment]
@loewenstein has this been fixed upstream already and pulled in via updates?

**Comment by voelzmo** [comment]
@cppforlife not at all fixed. Upstream committers didn't really respond to the issue so far. Did this happen on your side again? We couldn't find a good way to reproduce.

**Comment by voelzmo** [comment]
Closing this as supposedly this is fixed upstream
