### ISSUE TITLE
Validator creates snapshot but fails copying meta data

### ISSUE THREAD

**Issue by thardeck** [cloudfoundry-incubator/bosh-openstack-cpi-release#91]
Our validator pipeline fails with the latest bosh-openstack-cpi version while creating a snapshot. The snapshot is created but not reported as such so it is also not removed.

I will verify with the previous version if it is a regression or if the cloud environment changed in the mean time.

This is the stack trace:
```
Rescued Unknown: undefined method `+' for nil:NilClass. backtrace: /usr/lib64/bosh-openstack-cpi-release/bosh_openstack_cpi/lib/cloud/openstack/cloud.rb:549:in `block in snapshot_disk'
/usr/lib64/bosh-openstack-cpi-release/bosh_openstack_cpi/vendor/bundle/ruby/2.4.0/gems/bosh_common-1.3262.24.0/lib/common/thread_formatter.rb:49:in `with_thread_name'
/usr/lib64/bosh-openstack-cpi-release/bosh_openstack_cpi/lib/cloud/openstack/cloud.rb:513:in `snapshot_disk'
/usr/lib64/bosh-openstack-cpi-release/bosh_openstack_cpi/vendor/bundle/ruby/2.4.0/gems/bosh_cpi-2.3.0/lib/bosh/cpi/cli.rb:82:in `public_send'
/usr/lib64/bosh-openstack-cpi-release/bosh_openstack_cpi/vendor/bundle/ruby/2.4.0/gems/bosh_cpi-2.3.0/lib/bosh/cpi/cli.rb:82:in `run'
/usr/lib64/bosh-openstack-cpi-release/bosh_openstack_cpi/bin/openstack_cpi:21:in `block in <top (required)>'
/usr/lib64/bosh-openstack-cpi-release/ruby_openstack_cpi/lib/ruby/2.4.0/tmpdir.rb:89:in `mktmpdir'
/usr/lib64/bosh-openstack-cpi-release/bosh_openstack_cpi/bin/openstack_cpi:17:in `<top (required)>'
/usr/lib64/bosh-openstack-cpi-release/ruby_openstack_cpi/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/cli/exec.rb:74:in `load'
/usr/lib64/bosh-openstack-cpi-release/ruby_openstack_cpi/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/cli/exec.rb:74:in `kernel_load'
/usr/lib64/bosh-openstack-cpi-release/ruby_openstack_cpi/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/cli/exec.rb:27:in `run'
/usr/lib64/bosh-openstack-cpi-release/ruby_openstack_cpi/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/cli.rb:362:in `exec'
/usr/lib64/bosh-openstack-cpi-release/ruby_openstack_cpi/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/usr/lib64/bosh-openstack-cpi-release/ruby_openstack_cpi/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/usr/lib64/bosh-openstack-cpi-release/ruby_openstack_cpi/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
/usr/lib64/bosh-openstack-cpi-release/ruby_openstack_cpi/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/cli.rb:22:in `dispatch'
/usr/lib64/bosh-openstack-cpi-release/ruby_openstack_cpi/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
/usr/lib64/bosh-openstack-cpi-release/ruby_openstack_cpi/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/cli.rb:13:in `start'
/usr/lib64/bosh-openstack-cpi-release/ruby_openstack_cpi/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/exe/bundle:30:in `block in <top (required)>'
/usr/lib64/bosh-openstack-cpi-release/ruby_openstack_cpi/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/friendly_errors.rb:121:in `with_friendly_errors'
/usr/lib64/bosh-openstack-cpi-release/ruby_openstack_cpi/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/exe/bundle:22:in `<top (required)>'
/usr/lib64/bosh-openstack-cpi-release/ruby_openstack_cpi/bin/bundle:23:in `load'
/usr/lib64/bosh-openstack-cpi-release/ruby_openstack_cpi/bin/bundle:23:in `<main>'I, [2017-09-25T08:32:36.575964 #116]  INFO -- [req_id 294080]: Starting snapshot_disk...
```

**Comment by voelzmo** [comment]
Hey @thardeck thanks for reporting this. Indeed, the validator doesn't provide the necessary metadata that BOSH provides, see the take snapshot test: https://github.com/cloudfoundry-incubator/cf-openstack-validator/blob/1c7805c7fc1d90a6171c1f63ae99a1ecf95bd60d/src/specs/cpi_lifecycle_spec.rb#L128

The validator isn't yet ready to be used with CPI >=v34, we're going to fix this in the near future.

**Comment by voelzmo** [comment]
Fixed in recent validator version.
